@host={{$projectUrl}}
@email=test@example.com
@password=password

### Get token

# @name tokens
POST {{host}}/v1/accounts/oauth/tokens
Content-Type: application/json

{
  "grant_type": "password",
  "username": "{{email}}",
  "password": "{{password}}"
}

### Get token with refresh token

# @name refresh
POST {{host}}/v1/accounts/oauth/tokens
Content-Type: application/json

{
  "grant_type": "refresh_token",
  "refresh_token": "{{tokens.response.body.$.refresh_token}}"
}

### Get token from refresh token

POST {{host}}/v1/accounts/oauth/tokens
Content-Type: application/json

{
  "grant_type": "refresh_token",
  "refresh_token": "{{refresh.response.body.$.refresh_token}}"
}
