@host={{$projectUrl}}
@email=testing@beseler.net
@password=password
@emailConfirmToken=1

### Register account

POST {{host}}/v1/accounts/register-user
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "given_name": "Adam",
  "family_name": "Beseler"
}

### Login account

# @name login
POST {{host}}/v1/accounts/oauth/tokens
Content-Type: application/json

{
  "grant_type": "password",
  "username": "{{email}}",
  "password": "{{password}}"
}

### Resend email confirmation

POST {{host}}/v1/accounts/resend-email-confirmation
Authorization: Bearer {{login.response.body.$.access_token}}

### Confirm email

POST {{host}}/v1/accounts/confirm-email
Authorization: Bearer {{emailConfirmToken}}

### Forgot password

POST {{host}}/v1/accounts/forgot-password
Content-Type: application/json

{
  "email": "test@example.com"
}

### Reset password

POST {{host}}/v1/accounts/reset-password
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
  "password": "newpassword"
}
