@host={{$projectUrl}}
@email=test@example.com
@password=password
@emailConfirmToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2xvY2FsaG9zdCIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0IiwiZXhwIjoxNzQwNzE3MzQ4LCJpYXQiOjE3NDA3MTY3NDgsInN1YiI6MSwianRpIjoiMDE5NTRhY2QtYjA2NC03MTI4LTk3MzAtOTNmY2FiODVhYjZjIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5iZiI6MTc0MDcxNjc0OH0.sNC5rGwEFp7nNgjOaSSfudhrSOYTbBlw3iFJXTndvRA

### Register account

POST {{host}}/v1/accounts/register-user
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "givenName": "Adam",
  "familyName": "Beseler"
}

### Login account

# @name login
POST {{host}}/v1/accounts/oauth/tokens
Content-Type: application/json

{
  "grant_type": "password",
  "username": "{{email}}",
  "password": "{{password}}"
}

### Resend email confirmation

POST {{host}}/v1/accounts/resend-email-confirmation
Authorization: Bearer {{login.response.body.$.access_token}}

### Confirm email

POST {{host}}/v1/accounts/confirm-email
Authorization: Bearer {{emailConfirmToken}}

### Forgot password

POST {{host}}/v1/accounts/forgot-password
Content-Type: application/json

{
  "email": "test@example.com"
}

### Reset password

POST {{host}}/v1/accounts/reset-password
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
  "password": "newpassword"
}
