#@host=https://api.beseler.net
@host={{$projectUrl}}

###

POST {{host}}/v1/webhooks/azure-events
Content-Type: application/json

{
  "test": "example",
  "id": 42
}

###

OPTIONS {{host}}/v1/webhooks/azure-events
WebHook-Request-Origin: https://example.com
WebHook-Request-Rate: 50

