#@host=https://api.beseler.net
@host={{$projectUrl}}

### test webhook for email events

OPTIONS {{host}}/v1/webhooks/azure-events
WebHook-Request-Origin: https://example.com
WebHook-Request-Rate: 50

