#@host=https://api.beseler.net
@host={{$projectUrl}}
@communicationId="com-123"

### test webhook for email events

POST {{host}}/v1/webhooks/senedgrid-events
Content-Type: application/json

[
  {
    "email": "test@example.com", "timestamp": {{$timestamp}}, "sg_event_id": "sg-1", "communication_id": "{{communicationId}}",
    "event": "processed"
  },
  {    
    "email": "test@example.com", "timestamp": {{$timestamp}}, "sg_event_id": "sg-1", "communication_id": "{{communicationId}}",
    "event": "deferred",
    "attempt": "1"
  },
  {    
    "email": "test@example.com", "timestamp": {{$timestamp}}, "sg_event_id": "sg-1", "communication_id": "{{communicationId}}",
    "event": "bounce",
    "type": "bounced",
    "bounce_classification": "example_classification"
  },
  {    
    "email": "test@example.com", "timestamp": {{$timestamp}}, "sg_event_id": "sg-1", "communication_id": "{{communicationId}}",
    "event": "delivered"
  },
  {    
    "email": "test@example.com", "timestamp": {{$timestamp}}, "sg_event_id": "sg-1", "communication_id": "{{communicationId}}",
    "event": "open"
  },
]
