/* Migration
{
    "title": "00:createTable"
}
*/
CREATE TABLE event_log (
    event_id UUID NOT NULL,
    event_type TEXT NOT NULL,
    event_data JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    CONSTRAINT pk_event_log PRIMARY KEY (event_id)
);

/* Migration
{
    "title": "01:createIndex"
}
*/
CREATE INDEX idx_event_log_created_at ON event_log (occurred_at);
