/* Migration
{
    "title": "00:createTable"
}
*/
CREATE TABLE event_log (
    event_id UUID NOT NULL,
    resource TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    details JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    CONSTRAINT pk_event_log PRIMARY KEY (event_id)
);

/* Migration
{
    "title": "01:createIndex"
}
*/
CREATE INDEX idx_event_log_resource_id_occurred_at ON event_log (resource_id, occurred_at DESC);
