#@host=https://api.beseler.net
@host={{$projectUrl}}

### test webhook for email events

POST {{host}}/webhooks/email-events
Content-Type: application/json

{
  "email": "test@example.com",
  "timestamp": 123456789,
  "event": "example",
  "sg_event_id": "id-123"
}
