name: Continuous Integration

on:
  push:
    branches:
      - 'main'

jobs:
  build-sites:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: abeseler/beseler-net-dbdeploy
            dockerfile: src/beseler-net-dbdeploy.Dockerfile
            context: ./data
          - image: abeseler/beseler-dev-web
            dockerfile: src/beseler-dev-web.Dockerfile
            context: ./src
          - image: abeseler/beseler-net-api
            dockerfile: src/beseler-net-api.Dockerfile
            context: ./src
          - image: abeseler/beseler-net-web
            dockerfile: src/beseler-net-web.Dockerfile
            context: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}